language: node_js
node_js:
- '0.12'
- '0.10'
- iojs

cache:
  directories:
  - node_modules

after_success:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: ops@groupbyinc.com
  skip_cleanup: true,
  api_key: $NPM_API_KEY
  on:
    tags: true
    node: '0.12'
