defaults:
  node_cache: &node_cache
    key: v-{{ .Environment.CACHE_VERSION }}-api-javascript-{{ .Branch }}-{{ checksum "yarn.lock" }}

version: 2

jobs:
  build:
    working_directory: ~/api-javascript
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          <<: *node_cache
      - run:
          name: Install
          command: yarn
      - save_cache:
          <<: *node_cache
          paths:
            - ~/node_modules
  unit_test:
    working_directory: ~/api-javascript
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          <<: *node_cache
      - run:
          name: Test
          command: yarn start ci
  release:
    working_directory: ~/api-javascript
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          <<: *node_cache
      - run:
          name: Release
          command: yarn start release || true

workflows:
  version: 2

  build_test_release:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - release:
          context: org-global
          filters:
            branches:
              only: develop
          requires:
            - unit_test
